function [vocab, assignment] = build_vocabulary(features, k)
    % Build vocabulary from the descriptors using k-means. Output is a
    % 128xk matrix where each column is a cluster centroid. Optionally it
    % can return the assignment of the data to the clusters.
    % - ARGUMENTS
    %       features_decriptors     the features and descriptors cell array
    %                               generated by `extract_features_descriptors`
    %       k                       the vocabulary size (i.e. number of clusters)
    %       filename                
    % - OUTPUT
    %       vocab                   128xk matrix of cluster centroids
    %       assignment              row vector assignments of each image in
    %                               the data set.
    
    % Get descriptors from input.
    
    % Create descriptors array where each column is a descriptor.
    descriptors = features(:,:,2);
    descriptors_matrix = zeros(128, 0);
    for i=1:size(descriptors, 1)
        for j=1:size(descriptors,2)
            descriptors_matrix = horzcat(descriptors_matrix, descriptors{i,j});
        end
    end
    
    % Cluster descriptors using k-means.
    % TODO: we can specify different algorithm tweaks for k-means. Could be
    % a good experiment.
    [vocab, assignment] = vl_kmeans(single(descriptors_matrix), k);
    vocab = single(vocab);
end