function [vocab, assignment] = build_vocabulary(features_descriptors, k, vocab_name)
    % Build vocabulary from the descriptors using k-means. Output is a
    % 128xk matrix where each column is a cluster centroid. Optionally it
    % can return the assignment of the data to the clusters. Both outputs
    % are saved to `./vocabularies/<vocab_name>/` as `vocab` and
    % `assignment`.
    % - ARGUMENTS
    %       features_decriptors     the features and descriptors cell array
    %                               generated by `extract_features_descriptors`
    %       k                       the vocabulary size (i.e. number of clusters)
    %       filename                
    % - OUTPUT
    %       vocab                   128xk matrix of cluster centroids
    %       assignment              row vector assignments of each image in
    %                               the data set.
    
    % Get descriptors from input.
    descriptors = features_descriptors{:,:,2};
    descriptors = single(descriptors);
    
    % Clusters descriptors using k-means.
    % TODO: we can specify different algorithm tweaks for k-means. Could be
    % a good experiment.
    [vocab, assignment] = vl_kmeans(descriptors, k);
    
    save_path = fullfile('vocabularies', vocab_name);
    if ~exist(save_path, 'dir')
        mkdir(save_path)
    end
    save(fullfile(save_path, 'vocab'), 'vocab');
    save(fullfile(save_path, 'assignment'), 'assignment');
end